package exceptionhandling;

public  class TestingFinal2 {

	public static void main(String[] args) {
		
		

	}
	
	public void test1()
	{
		
		
	}

}
